# size of the file in 'M' 
# corresponds with the container env var FILE_SIZE
file_size: 5Gi

max_files: 1000

min_files: 500

# size of the PVCs to be created to store sample files
pvc_size: 6Gi

buffer: 10Mi

namespace: dvm-retry-test

deployment_name: test-02

# pause_operations pauses the random file operations
pause_operations: true

pvc_name: pvc-02

image: quay.io/pranavgaikwad/data-generator:latest

destroy: false
